## https://github.com/openai/codex/blob/main/docs/config.md

model                  = "gpt-5.2-codex"
model_reasoning_effort = "medium"
sandbox_mode           = "workspace-write"
approval_policy        = "on-failure"
file_opener            = "vscode-insiders"

[history]
persistence = "save-all"
max_bytes   = 5000000 ## 5 MB

[features]
shell_tool         = true ## Enable the default `shell` tool
undo               = true ## Enable undo via per-turn git ghost snapshots
web_search_request = true ## Allow the model to issue web searches

[sandbox_workspace_write]
network_access = true
