[tools]
1password-cli = "2.30.3"  ## For password management
bun           = "1.3.1"
github-cli    = "2.82.1"
go            = "1.25.5"  ## For golang package management
jq            = "1.8.1"
nodejs        = "22.12.0" ## For node runtime
python        = "3.13.1"  ## For python runtime
rust          = "1.89.0"
fastfetch     = "2.54.0"
yq            = "4.48.1"
chezmoi       = "2.69.1"
usage         = "2.12.0" ## Required by `mise completion`
uv            = "0.9.5"

[tool_alias]
1password-cli = "asdf:kc-workspace/asdf-1password"
fastfetch     = "github:fastfetch-cli/fastfetch"
yq            = "github:mikefarah/yq"
chezmoi       = "github:twpayne/chezmoi"

[settings]
disable_backends                    = ["spm", "dotnet", "gem", "ubi"]
not_found_auto_install              = true
use_versions_host                   = false ## NOTE: https://github.com/jdx/mise/discussions/4878
pin                                 = true
idiomatic_version_file_enable_tools = ["node"]

[settings.status]
show_env      = true
show_tools    = true
missing_tools = "always"
truncate      = false

[settings.npm]
package_manager = "bun"

[settings.pipx]
uvx = true

[env]
_.file = '.env'

