[env]
AWS_PROFILE = "cognius-dev"
KUBECONFIG = "{{env.HOME}}/.kube/works/config.st"

[tasks.ka]
description = 'Run kubectl with admin permissions'
run = "kubectl --context prd:smt2/a"

[tasks.kdebug]
description = 'Create debug pod on kube with admin permissions'
run = "kubectl --context prd:smt2/a run debug --namespace default --image=kamontat/dotfiles:latest --image-pull-policy=Always --restart=Never -it --rm"

[tasks.ha]
description = 'Run helm with admin permissions'
run = "helm --kube-context prd:smt2/a"

[tools]
aws-cli = "2.31.20"
helm = "3.19.0"
kubectl = "1.32.9"
shfmt = "3.12.0"
shellcheck = "0.11.0"

[settings]
experimental = true

